services:
  api:
    image: cs-api
    container_name: cs-api
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - loki

networks:
  loki:
